version: '3.3'

services:
  postgraphile:
    image: postgraphile:1.0
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      postgres_postgres:


networks:
  postgres_postgres:
    external: true
